#!/bin/bash
# VU Attendy - Icon Generator Helper
# This script helps create app icons for PWA and app stores

echo "=== VU Attendy Icon Creator ==="
echo ""
echo "You need to create two icon files:"
echo ""
echo "1. icon-192.png"
echo "   - Size: 192 × 192 pixels"
echo "   - Used for: Android home screen, PWA"
echo ""
echo "2. icon-512.png"
echo "   - Size: 512 × 512 pixels"
echo "   - Used for: App stores, splash screens"
echo ""
echo "Design Tips:"
echo "- Vape Ustad brand colors: Orange (#f97316) and Grey (#d4d4d8)"
echo "- Simple, bold design"
echo "- Center logo/text with padding"
echo "- No gradients or translucency"
echo ""
echo "Quick Options:"
echo "1. Use Canva (free online design tool)"
echo "2. Use GIMP / Photoshop"
echo "3. Use Figma (free)"
echo "4. Use online icon generator at https://www.favicon-generator.org/"
echo ""
echo "After creating icons, save them to the project root:"
echo "  /workspaces/VU-ATTENDY-/icon-192.png"
echo "  /workspaces/VU-ATTENDY-/icon-512.png"
echo ""
echo "Commands to check if icons exist:"
echo "  ls -lh /workspaces/VU-ATTENDY-/icon-*.png"
